export const DRAWER_OPEN = 'DRAWER_OPEN'
export const DRAWER_CLOSE = 'DRAWER_CLOSE'

export const USER_EDIT_DRAWER_OPEN = 'USER_EDIT_DRAWER_OPEN'
export const USER_EDIT_DRAWER_CLOSE = 'USER_EDIT_DRAWER_CLOSE'